---
name: Module-Pluggable
version: 3.1
author:
  - 'Simon Wistow <simon@thegestalt.org>'
abstract: automatically give your module the ability to have plugins
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Inspector: 0
  File::Basename: 0
  File::Spec: 3.00
  Test::More: 0.62
provides:
  Devel::InnerPackage:
    file: lib/Devel/InnerPackage.pm
    version: 0.3
  Module::Pluggable:
    file: lib/Module/Pluggable.pm
    version: 3.1
  Module::Pluggable::Object:
    file: lib/Module/Pluggable/Object.pm
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
