--- #YAML:1.0
name: Module-Pluggable
version: 1.9
author:
  - Simon Wistow <simon@thegestalt.org>
abstract: |-
  automatically give your module the ability to have plugins
license: perl
requires:
  File::Basename: 0
  File::Find::Rule: 0
  File::Spec::Functions: 0
  Test::More: 0
  UNIVERSAL::require: 0
provides:
  Module::Pluggable:
    file: lib/Module/Pluggable.pm
    version: 1.9
generated_by: Module::Build version 0.25
