---
name: Module-Pluggable
version: 3.0
author:
  - Simon Wistow <simon@thegestalt.org>
abstract: automatically give your module the ability to have plugins
license: perl
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  Test::More: 0
provides:
  Devel::InnerPackage:
    file: lib/Devel/InnerPackage.pm
    version: 0.1
  Module::Pluggable:
    file: lib/Module/Pluggable.pm
    version: 3.0
  Module::Pluggable::Object:
    file: lib/Module/Pluggable/Object.pm
generated_by: Module::Build version 0.2611
