# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Pluggable
version:      2.6
version_from: lib/Module/Pluggable.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Spec::Functions:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
