---
name: Module-Pluggable
version: 2.96
author:
  - Simon Wistow <simon@thegestalt.org>
abstract: automatically give your module the ability to have plugins
license: perl
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  Test::More: 0
provides:
  Module::Pluggable:
    file: lib/Module/Pluggable.pm
    version: 2.96
generated_by: Module::Build version 0.25
